import { caseStudies, casePath, servicePath, services, SITE_URL } from "../content/site";
import { industries, industryPath } from "../content/industries";
import { getPublishedPosts } from "../lib/posts.server";

export async function loader() {
  const [english, spanish] = await Promise.all([getPublishedPosts("en", 50), getPublishedPosts("es", 50)]);
  const lines = ["# Puna Tech", "", "> Custom software, AI workflow automation, and systems integration for B2B operations. English is the default language; Spanish content lives under /es.", "", "## Core services", ...services.en.map((item) => `- [${item.eyebrow}](${SITE_URL}${servicePath("en", item.slug)}): ${item.description}`), ...services.es.map((item) => `- [${item.eyebrow}](${SITE_URL}${servicePath("es", item.slug)}): ${item.description}`), "", "## Industry solution guides", ...industries.en.map((item) => `- [${item.title}](${SITE_URL}${industryPath("en", item.slug)}): ${item.introduction}`), ...industries.es.map((item) => `- [${item.title}](${SITE_URL}${industryPath("es", item.slug)}): ${item.introduction}`), "", "## Case studies", ...caseStudies.en.map((item) => `- [${item.title}](${SITE_URL}${casePath("en", item.slug)}): ${item.summary}`), ...caseStudies.es.map((item) => `- [${item.title}](${SITE_URL}${casePath("es", item.slug)}): ${item.summary}`), "", "## Reviewed insights", ...english.map((post) => `- [${post.title}](${SITE_URL}/blog/${post.slug}): ${post.excerpt || ""}`), ...spanish.map((post) => `- [${post.title}](${SITE_URL}/es/blog/${post.slug}): ${post.excerpt || ""}`), "", "Only published, human-reviewed content is listed here. Public case studies use anonymized client identities and verified-only claims. Industry solution guides describe illustrative opportunities and never imply unverified client experience."];
  return new Response(lines.join("\n"), { headers: { "Content-Type": "text/plain; charset=utf-8", "Cache-Control": "public, max-age=0, s-maxage=3600" } });
}
