import type { LoaderFunctionArgs } from "react-router";
import { Form, Link } from "react-router";
import { ArrowRight, Mail, Search } from "lucide-react";
import { EmptyState, formatDate, OpsPageHeader, Pager, StatusBadge } from "../components/ops";
import { opsData, pageFrom, paginationRange, requireAdmin } from "../lib/admin.server";

const statuses = ["new", "qualified", "disqualified", "reviewed", "contacted", "do_not_contact"];

export async function loader({ request }: LoaderFunctionArgs) {
  const context = await requireAdmin(request); const url = new URL(request.url); const page = pageFrom(request); const { from, to } = paginationRange(page);
  const filters = { q: (url.searchParams.get("q") || "").trim().slice(0, 100), status: url.searchParams.get("status") || "", vertical: url.searchParams.get("vertical") || "", province: (url.searchParams.get("province") || "").trim().slice(0, 100), email: url.searchParams.get("email") === "yes", minScore: Math.max(0, Math.min(100, Number(url.searchParams.get("minScore") || 0) || 0)) };
  let query = context.service.from("prospect_accounts").select("id,business_name,category,vertical,province,city,website,public_email,score,status,collected_at", { count: "exact" }).order("score", { ascending: false }).order("collected_at", { ascending: false }).range(from, to);
  if (filters.q) query = query.ilike("business_name", `%${filters.q.replace(/[%_]/g, "")}%`); if (filters.status) query = query.eq("status", filters.status); if (filters.vertical) query = query.eq("vertical", filters.vertical); if (filters.province) query = query.ilike("province", `%${filters.province.replace(/[%_]/g, "")}%`); if (filters.email) query = query.not("public_email", "is", null); if (filters.minScore) query = query.gte("score", filters.minScore);
  const result = await query; if (result.error) throw new Response("No se pudieron cargar los prospectos.", { status: 500 });
  return opsData({ prospects: result.data || [], count: result.count, page, filters }, context.headers);
}

export default function OpsProspects({ loaderData }: { loaderData: { prospects: Array<Record<string, any>>; count: number | null; page: number; filters: { q: string; status: string; vertical: string; province: string; email: boolean; minScore: number } } }) {
  const params = new URLSearchParams(); Object.entries(loaderData.filters).forEach(([key, value]) => { if (value) params.set(key, value === true ? "yes" : String(value)); });
  return <><OpsPageHeader eyebrow="Adquisición" title="Prospectos de agencias LATAM" description="Priorizá evidencia y complejidad operativa. Aprobar un borrador nunca envía el email."/>
    <Form method="get" className="ops-filters ops-filters-wide"><label><span className="sr-only">Buscar negocio</span><Search aria-hidden="true"/><input type="search" name="q" defaultValue={loaderData.filters.q} placeholder="Buscar negocio…"/></label><label><span>Estado</span><select name="status" defaultValue={loaderData.filters.status}><option value="">Todos</option>{statuses.map((item) => <option key={item}>{item}</option>)}</select></label><label><span>Vertical</span><select name="vertical" defaultValue={loaderData.filters.vertical}><option value="">Todas</option><option value="automotive_dealers">Concesionarias</option><option value="agricultural_equipment">Maquinaria agrícola</option></select></label><label><span>Provincia</span><input name="province" defaultValue={loaderData.filters.province}/></label><label><span>Score mínimo</span><input name="minScore" type="number" min="0" max="100" defaultValue={loaderData.filters.minScore || ""}/></label><label className="ops-check"><input name="email" value="yes" type="checkbox" defaultChecked={loaderData.filters.email}/><span>Con email público</span></label><button className="ops-button ops-button-secondary">Filtrar</button></Form>
    {loaderData.prospects.length ? <div className="ops-table-wrap"><table className="ops-table"><thead><tr><th>Negocio</th><th>Ubicación</th><th>Score</th><th>Contacto</th><th>Estado</th><th><span className="sr-only">Abrir</span></th></tr></thead><tbody>{loaderData.prospects.map((prospect) => <tr key={prospect.id}><td data-label="Negocio"><strong>{prospect.business_name}</strong><small>{prospect.category || prospect.vertical}</small></td><td data-label="Ubicación">{[prospect.city, prospect.province].filter(Boolean).join(", ") || "—"}</td><td data-label="Score"><strong className="ops-score">{prospect.score}</strong><small> / 100</small></td><td data-label="Contacto">{prospect.public_email ? <span className="ops-email"><Mail aria-hidden="true" size={15}/>Email público</span> : <span className="ops-muted">Sin email</span>}</td><td data-label="Estado"><StatusBadge value={prospect.status}/></td><td data-label="Abrir"><Link className="ops-row-link" to={`/ops/prospects/${prospect.id}`}>Revisar <ArrowRight aria-hidden="true" size={16}/></Link></td></tr>)}</tbody></table></div> : <EmptyState title="No hay prospectos en esta vista" body="Quitá filtros o esperá la próxima ejecución semanal de n8n."/>}<Pager page={loaderData.page} count={loaderData.count} path="/ops/prospects" params={params}/>
  </>;
}
