export type { Locale } from "./chrome";
export {
  SITE_URL,
  CAL_LINK,
  CONTACT_EMAIL,
  CONTACT_WHATSAPP,
  homePath,
  servicePath,
  casePath,
  servicesHubPath,
  casesHubPath,
  blogPath,
  contactPath,
} from "./chrome";
export type { CaseStudyContent, ServiceContent } from "./catalog";
export {
  caseStudies,
  casesHubCopy,
  getCaseStudy,
  getService,
  legacyPostRedirects,
  services,
  servicesHubCopy,
} from "./catalog";
import { chromeCopy } from "./chrome";

export const copy = {
  en: {
    ...chromeCopy.en,
    heroLabClarification: "Lab SaaS products demonstrate how we ship and operate software; client delivery is the core business.",
    heroMicrocopy: "Fifteen minutes. The bottleneck, the options, the next useful step.",
    seeWork: "Explore our services",
    proof: ["From discovery through production launch", "Bilingual collaboration across the Americas", "Software, automation, and integrations in one team"],
    workLabEyebrow: "SaaS Lab",
    workLabTitle: "Lab demos · Proof of execution",
    workLabSubtitle: "Live products we ship ourselves to prove architecture and delivery standards—not the catalogue we sell.",
    workLabBadge: "Lab demo",
    workClientEyebrow: "Client Delivery",
    workClientTitle: "Client delivery · Production systems",
    workClientSubtitle: "Custom software, automations, and integrations built for specific operational bottlenecks. Client names stay private; outcomes and architectures stay concrete.",
    workClientBadge: "Client delivery",
    openCase: "Open case",
    liveDemo: "Live demo",
    viewArchitecture: "View delivery architecture",
    fitEyebrow: "Where Puna fits best",
    fitTitle: "For operations that have outgrown spreadsheets, manual handoffs, and disconnected tools.",
    fitBody: "We are most useful when the problem crosses product, data, and operations—not when the answer is another generic website or an AI demo.",
    fit: [
      ["Operational workflows", "Critical work coordinated across spreadsheets, inboxes, CRMs, and internal tools."],
      ["Digital products", "Customer and internal experiences that need reliable permissions, workflows, and ownership."],
      ["Connected systems", "Products that combine data, permissions, user accounts, and specialized workflows."],
    ],
    servicesEyebrow: "Three focused capabilities",
    servicesTitle: "Start with the bottleneck, not the technology.",
    servicesBody: "Each engagement is shaped around one operational outcome and a system your team can own.",
    casesEyebrow: "Selected work",
    casesTitle: "Real systems for work that could not stay manual.",
    casesBody: "The client names can stay private. The operating problem, architecture, and delivered system stay concrete.",
    slowdownEyebrow: "Find your starting point",
    slowdownTitle: "What is slowing your team down?",
    slowdowns: [
      ["Manual work keeps multiplying", "Process automation · AI workflows", "Map and automate the repetitive handoffs without removing human control."],
      ["Your tools do not agree", "Data & systems integration", "Create a reliable data path between the systems already running the operation."],
      ["The operation needs its own product", "Custom B2B software", "Build the portal, platform, or internal tool the workflow actually requires."],
    ],
    auditEyebrow: "The free bottleneck audit",
    auditTitle: "Fifteen focused minutes. One clearer next move.",
    auditSteps: [
      ["Map", "Show us where work stalls, repeats, or disappears between tools."],
      ["Frame", "We separate the process problem from the software problem."],
      ["Decide", "Leave with the most useful next step—even when that is not a build."],
    ],
    processEyebrow: "How we work",
    processTitle: "A short path from ambiguity to a working system.",
    process: [
      ["Discover", "Map the workflow, data, risks, and the business outcome that matters."],
      ["Design", "Define the smallest useful scope, system architecture, and user journey."],
      ["Build", "Ship in reviewable increments with visible technical decisions and QA."],
      ["Launch", "Deploy, document, measure adoption, and define the next improvement."],
    ],
    standardsEyebrow: "Built for ownership",
    standardsTitle: "Clear interfaces. Observable workflows. No black boxes.",
    standards: [
      ["Integration-first", "Connect the tools already running your operation instead of creating another isolated dashboard."],
      ["Human control", "Keep review and approval steps where financial, customer, or operational risk requires them."],
      ["Measurable delivery", "Define what success means before implementation and instrument the workflow from launch."],
    ],
    compareTitle: "When off-the-shelf is enough, and when custom is required",
    compareColumns: ["Off-the-shelf tool", "Custom software (Puna Tech)"],
    compareRows: [
      ["Fits when", "The process fits the product and native integrations are enough", "The handoff, the exception, or the data does not fit the product"],
      ["What you get", "Configuration or an extension of what you already run", "Your own system: automation, integrations, a portal, or an internal tool"],
      ["Ownership", "You depend on the vendor roadmap", "Your team runs it. Repos and access are written into the proposal"],
      ["Typical risk", "Forcing the process into the product’s mold", "Building too much when what you already run still works"],
      ["First step", "Connect or extend what you have", "Map the bottleneck in 15 min and decide whether to build"],
    ] as [string, string, string][],
    versusTitle: "Puna Tech versus other ways to solve it",
    versus: [
      ["Vs a generic agency.", "An agency usually works on the site, the brand, or campaigns. We build the system of the workflow: automation, data, and integrations your team can run."],
      ["Vs loose no-code.", "No-code is fine for prototypes and simple flows. When permissions, exceptions, CRM or ERP, and visible failures matter, you need engineering with an owner and an explicit handoff, not a chain of automations with no owner."],
      ["Vs “software for everyone”.", "We do not sell a horizontal SaaS or “AI for any industry.” The work is B2B operations in Argentina, and bilingual collaboration across the Americas, when the team outgrew off-the-shelf tools."],
    ] as [string, string][],
    faqTitle: "Common questions before the first call",
    faqs: [
      ["What kinds of projects are a fit?", "Operational platforms, AI-assisted workflows, data pipelines, and integrations where off-the-shelf software creates friction or leaves important gaps."],
      ["When is custom software better than an off-the-shelf tool?", "When a critical workflow needs specific roles, data rules, or integrations that standard tools cannot support cleanly. We first check whether your current tools can be connected or extended."],
      ["Do you replace our existing tools?", "Usually no. We first look for a reliable way to connect and extend your current stack. Replacement is recommended only when the existing constraint makes it necessary."],
      ["Can we start with a small scope?", "Yes. The first engagement should prove one useful outcome, expose the real integration risks, and leave a production-quality foundation for expansion."],
      ["How do you handle AI risk?", "We use structured outputs, validation, permissions, logging, and human approval for consequential actions. The exact controls depend on the workflow."],
      ["Are you the same company as PUNA Software Factory?", "No. PUNA Software Factory is based in Salta (punasoftwarefactory.com.ar). We are Puna Tech (puna-tech.com), a Buenos Aires software factory: custom software, automation, and integrations for B2B operations."],
      ["Do you automate business operations in Argentina?", "Yes. We design and ship custom software to automate B2B operations in Argentina, with bilingual collaboration when the project spans the Americas."],
      ["How are you different from other software factories?", "Other factories may be the right fit depending on scope. We fit when the bottleneck is a concrete operational workflow (automation, integration, or an internal tool) and the team needs a system it can run."],
      ["How much does it cost to automate one process?", "It depends on the process: discovery, how many integrations, third-party licenses, and what has to be maintained afterward. We do not publish a price. Scope sets the investment, and we talk budget in private. In 15 minutes we frame what is in and what is out, not a quote."],
      ["If we hire custom work, who owns the code, the repo, and the access?", "Ownership, repositories, and access are written into the proposal. We build so your team can run and extend the system without a hidden lock-in."],
      ["Zapier, n8n, Make, or custom development?", "Zapier, n8n, or Make is enough when the process fits, someone can maintain it, and exceptions are few. When the handoff, the exception, or the data is the work, and the flow cannot live in one person’s account, you need custom engineering or an integration with an owner. If a connector closes the case, we say so: custom build is not required."],
      ["Our SaaS is too small for the exceptions. When do we go custom?", "Stay on SaaS if the process is industry-standard and the vendor’s integrations cover it. Go custom when the business rule does not fit the product, when a parallel spreadsheet is already the real system, or when a critical handoff is not recorded anywhere."],
    ],
    finalTitle: "Bring us the workflow your team has learned to work around.",
    finalBody: "In 15 minutes, we will map the constraint and decide whether software, automation, integration—or no build at all—is the useful next step.",
    briefTitle: "Prefer to write it down?",
    briefBody: "Send a short project brief. We will reply with the next useful question—not an automated sales sequence.",
    blogTitle: "Practical notes on software and operations",
    blogBody: "Evidence-backed guides, implementation lessons, and case-study analysis. Every article is reviewed before publication.",
    readMore: "Read more",
    emptyBlog: "Editorial work is in review. New articles will appear here after human approval.",
    latamEyebrow: "Buenos Aires · LATAM-AR",
    latamTitle: "Software factory in Argentina and LATAM for B2B operations.",
    latamBody: "Puna Tech (Buenos Aires) is a software factory that designs and ships custom software to automate B2B operations in Argentina: process automation, integrations (CRM, ERP, APIs), and systems the team can run. Lab SaaS proves execution; client delivery is the business.",
    latamPoints: [
      ["Custom software · internal tools", "Platforms and portals shaped to your workflows."],
      ["Process automation with human control", "Handoffs with validation where risk requires it."],
      ["CRM / ERP / API integration", "Reliable corridors with visible failures."],
      ["Explicit ownership · no hidden lock-in", "Repos, access, and infrastructure in the proposal."],
      ["Bilingual collaboration across the Americas", "US and LATAM stakeholders in one engagement."],
    ],
  },
  es: {
    ...chromeCopy.es,
    heroLabClarification: "Los productos SaaS del lab demuestran cómo construimos y operamos software; la entrega a clientes es el negocio principal.",
    heroMicrocopy: "Quince minutos. El cuello de botella, las opciones y el próximo paso útil.",
    seeWork: "Explorar servicios",
    proof: ["De discovery al lanzamiento productivo", "Colaboración bilingüe en todo el continente", "Software, automatización e integraciones en un solo equipo"],
    workLabEyebrow: "Laboratorio SaaS",
    workLabTitle: "Demos de lab · Prueba de ejecución",
    workLabSubtitle: "Productos en vivo que construimos nosotros para probar arquitectura y estándar de entrega—no el catálogo que vendemos.",
    workLabBadge: "Demo de lab",
    workClientEyebrow: "Entrega a Clientes",
    workClientTitle: "Entrega a clientes · Sistemas en producción",
    workClientSubtitle: "Software a medida, automatizaciones e integraciones para cuellos de botella específicos. Nombres en reserva; resultados y arquitecturas concretas.",
    workClientBadge: "Entrega a cliente",
    openCase: "Abrir caso",
    liveDemo: "Demo en vivo",
    viewArchitecture: "Ver arquitectura de entrega",
    fitEyebrow: "Dónde encaja mejor Puna",
    fitTitle: "Para operaciones que ya superaron las planillas, los traspasos manuales y las herramientas desconectadas.",
    fitBody: "Somos más útiles cuando el problema cruza producto, datos y operaciones, no cuando la respuesta es otro sitio genérico o una demo de IA.",
    fit: [
      ["Flujos operativos", "Trabajo crítico coordinado entre planillas, correos, CRMs y herramientas internas."],
      ["Productos digitales", "Experiencias internas y de clientes que necesitan permisos, flujos y propiedad confiables."],
      ["Sistemas conectados", "Productos que combinan datos, permisos, cuentas de usuario y flujos especializados."],
    ],
    servicesEyebrow: "Tres capacidades enfocadas",
    servicesTitle: "Empezamos por el cuello de botella, no por la tecnología.",
    servicesBody: "Cada proyecto se organiza alrededor de un resultado operativo y un sistema que tu equipo pueda comprender y operar.",
    casesEyebrow: "Trabajo seleccionado",
    casesTitle: "Sistemas reales para trabajo que no podía seguir siendo manual.",
    casesBody: "Los nombres pueden permanecer privados. El problema operativo, la arquitectura y el sistema entregado se muestran con claridad.",
    slowdownEyebrow: "Encontrá el punto de partida",
    slowdownTitle: "¿Qué está frenando a tu equipo?",
    slowdowns: [
      ["El trabajo manual no deja de crecer", "Automatización de procesos con IA", "Mapeamos y automatizamos traspasos repetitivos sin eliminar el control humano."],
      ["Tus herramientas no se ponen de acuerdo", "Integración de datos y sistemas", "Creamos un recorrido confiable entre los sistemas que ya sostienen la operación."],
      ["La operación necesita un producto propio", "Software B2B a medida", "Construimos el portal, la plataforma o la herramienta interna que el flujo necesita."],
    ],
    auditEyebrow: "La auditoría gratuita",
    auditTitle: "Quince minutos enfocados. Un próximo paso más claro.",
    auditSteps: [
      ["Mapear", "Mostranos dónde el trabajo se detiene, se repite o se pierde entre herramientas."],
      ["Enmarcar", "Separamos el problema del proceso del problema de software."],
      ["Decidir", "Te llevás el próximo paso más útil, incluso si no implica construir nada."],
    ],
    processEyebrow: "Cómo trabajamos",
    processTitle: "Un recorrido corto desde la ambigüedad hasta un sistema funcionando.",
    process: [
      ["Descubrir", "Mapeamos el flujo, los datos, los riesgos y el resultado de negocio relevante."],
      ["Diseñar", "Definimos el alcance mínimo útil, la arquitectura y la experiencia de usuario."],
      ["Construir", "Entregamos avances revisables con decisiones técnicas visibles y control de calidad."],
      ["Lanzar", "Desplegamos, documentamos, medimos adopción y definimos la siguiente mejora."],
    ],
    standardsEyebrow: "Construido para dar control",
    standardsTitle: "Interfaces claras. Flujos observables. Sin cajas negras.",
    standards: [
      ["Integración primero", "Conectamos las herramientas que ya sostienen la operación antes de sumar otro sistema aislado."],
      ["Control humano", "Conservamos revisión y aprobación donde existe riesgo financiero, operativo o de clientes."],
      ["Entrega medible", "Definimos qué significa éxito antes de implementar e instrumentamos el flujo desde el lanzamiento."],
    ],
    compareTitle: "¿Cuándo alcanza lo estándar y cuándo hace falta a medida?",
    compareColumns: ["Herramienta estándar", "Software a medida (Puna Tech)"],
    compareRows: [
      ["Encaja cuando", "El proceso cabe en el producto y las integraciones nativas bastan", "El handoff, la excepción o el dato no caben en el producto"],
      ["Qué obtenés", "Configuración o extensión de lo que ya usan", "Sistema propio: automatización, integraciones, portal o herramienta interna"],
      ["Propiedad", "Dependés del roadmap del proveedor", "El equipo lo opera. Repos y accesos quedan escritos en la propuesta"],
      ["Riesgo típico", "Forzar el proceso al molde del software", "Construir de más cuando lo que ya usan todavía alcanza"],
      ["Primer paso", "Conectar o extender lo que ya tienen", "Mapear el cuello de botella en 15 min y decidir si construir"],
    ] as [string, string, string][],
    versusTitle: "Puna Tech frente a otras formas de resolverlo",
    versus: [
      ["Vs agencia genérica.", "Una agencia suele trabajar sitio, marca o campañas. Nosotros armamos el sistema del flujo: automatización, datos e integraciones que el equipo puede operar."],
      ["Vs no-code suelto.", "El no-code sirve para prototipos y flujos simples. Cuando hay permisos, excepciones, CRM o ERP, y las fallas tienen que verse, hace falta ingeniería con dueño y handoff explícito, no una cadena de automatizaciones sin dueño."],
      ["Vs “software para todos”.", "No vendemos un SaaS horizontal ni “IA para cualquier industria”. El trabajo es operaciones B2B en Argentina, y colaboración bilingüe en las Américas, cuando el equipo ya superó las herramientas estándar."],
    ] as [string, string][],
    faqTitle: "Preguntas frecuentes antes de la primera llamada",
    faqs: [
      ["¿Qué proyectos encajan mejor?", "Plataformas operativas, flujos asistidos por IA, pipelines de datos e integraciones donde el software estándar genera fricción o deja vacíos importantes."],
      ["¿Cuándo conviene el software a medida frente a uno estándar?", "Cuando un flujo crítico necesita permisos, reglas de datos o integraciones que las herramientas estándar no resuelven bien. Primero evaluamos si se pueden conectar o extender las herramientas actuales."],
      ["¿Reemplazan nuestras herramientas actuales?", "En general, no. Primero buscamos conectar y extender el stack actual. Recomendamos reemplazarlo solo cuando la limitación existente lo vuelve necesario."],
      ["¿Podemos empezar con un alcance pequeño?", "Sí. El primer proyecto debe demostrar un resultado útil, revelar los riesgos reales de integración y dejar una base de producción que pueda crecer."],
      ["¿Cómo controlan el riesgo de la IA?", "Usamos salidas estructuradas, validaciones, permisos, registros y aprobación humana para acciones sensibles. Los controles exactos dependen del flujo."],
      ["¿Son la misma empresa que PUNA Software Factory?", "No. PUNA Software Factory opera desde Salta (punasoftwarefactory.com.ar). Nosotros somos Puna Tech (puna-tech.com), software factory en Buenos Aires: software a medida, automatización e integraciones para operaciones B2B."],
      ["¿Automatizan operaciones de empresas en Argentina?", "Sí. Diseñamos y entregamos software a medida para automatizar operaciones B2B en Argentina, con colaboración bilingüe cuando el proyecto cruza las Américas."],
      ["¿En qué se diferencian de otras software factories?", "Otras factories pueden ser la opción correcta según el alcance. Nosotros encajamos cuando el cuello de botella es un flujo operativo concreto (automatización, integración o herramienta interna) y el equipo necesita un sistema que pueda operar."],
      ["¿Cuánto cuesta automatizar un proceso?", "Depende del proceso: el relevamiento, cuántas integraciones hacen falta, las licencias de terceros y qué hay que mantener después. No publicamos un precio. El alcance define la inversión, y el presupuesto lo vemos en privado. En 15 minutos acotamos qué entra y qué no, no una cotización."],
      ["Si contratamos a medida, ¿de quién queda el código, el repo y los accesos?", "La propiedad, los repositorios y los accesos quedan escritos en la propuesta. Construimos para que tu equipo pueda operar y extender el sistema sin dependencia oculta."],
      ["¿Zapier, n8n, Make o desarrollo a medida?", "Zapier, n8n o Make alcanzan cuando el proceso cabe, hay alguien que lo mantiene y las excepciones son pocas. Cuando el handoff, la excepción o el dato son el trabajo, y el flujo no puede vivir en la cuenta de una sola persona, hace falta ingeniería a medida o una integración con dueño. Si un conector cierra el caso, lo decimos: no hace falta construir a medida."],
      ["El SaaS nos queda chico en las excepciones. ¿Cuándo pedimos a medida?", "Seguí en SaaS si el proceso es el del rubro y las integraciones del proveedor alcanzan. Pedí a medida cuando la regla de negocio no entra en el producto, cuando una planilla paralela ya es el sistema real, o cuando el handoff crítico no queda registrado en ninguna herramienta."],
    ],
    finalTitle: "Contanos qué proceso aprendió tu equipo a soportar todos los días.",
    finalBody: "En 15 minutos mapeamos la restricción y definimos si el próximo paso útil es software, automatización, integración o no construir todavía.",
    briefTitle: "¿Preferís explicarlo por escrito?",
    briefBody: "Enviá un brief corto. Te responderemos con la siguiente pregunta útil, no con una secuencia automática de ventas.",
    blogTitle: "Notas prácticas sobre software y operaciones",
    blogBody: "Guías con evidencia, aprendizajes de implementación y análisis de casos. Cada artículo se revisa antes de publicarse.",
    readMore: "Leer más",
    emptyBlog: "El contenido editorial está en revisión. Los nuevos artículos aparecerán después de la aprobación humana.",
    latamEyebrow: "Buenos Aires · LATAM-AR",
    latamTitle: "Software factory en Argentina y LATAM para operaciones B2B.",
    latamBody: "Puna Tech (Buenos Aires) es una software factory que diseña y entrega software a medida para automatizar operaciones B2B en Argentina: automatización de procesos, integraciones (CRM, ERP, APIs) y sistemas que el equipo puede operar. El lab SaaS prueba ejecución; la entrega a clientes es el negocio.",
    latamPoints: [
      ["Software a medida · herramientas internas", "Plataformas y portales armados alrededor de tus flujos."],
      ["Automatización de procesos con IA", "Traspasos con validación y control humano donde el riesgo lo pide."],
      ["Integración CRM / ERP / APIs", "Corredores confiables con fallas visibles."],
      ["Propiedad explícita · sin lock-in oculto", "repositorios, accesos e infraestructura en la propuesta."],
      ["Colaboración bilingüe en las Américas", "Stakeholders en LATAM y EE.UU. en el mismo proyecto."],
    ],
  },
};
