import { index, route, type RouteConfig } from "@react-router/dev/routes";

export default [
  index("./routes/home.tsx", { id: "home-en" }),
  route("es", "./routes/home.tsx", { id: "home-es" }),
  route("services/:slug", "./routes/service.tsx", { id: "service-en" }),
  route("es/servicios/:slug", "./routes/service.tsx", { id: "service-es" }),
  route("for-agencies", "./routes/legacy-industry-redirect.ts", { id: "legacy-agencies-en" }),
  route("es/para-agencias", "./routes/legacy-industry-redirect.ts", { id: "legacy-agencies-es" }),
  route("industries/:slug", "./routes/legacy-industry-redirect.ts", { id: "legacy-industry-en" }),
  route("es/industrias/:slug", "./routes/legacy-industry-redirect.ts", { id: "legacy-industry-es" }),
  route("case-studies/:slug", "./routes/case-study.tsx", { id: "case-en" }),
  route("es/casos/:slug", "./routes/case-study.tsx", { id: "case-es" }),
  route("blog", "./routes/blog-index.tsx", { id: "blog-en" }),
  route("es/blog", "./routes/blog-index.tsx", { id: "blog-es" }),
  route("blog/:slug", "./routes/blog-post.tsx", { id: "post-en" }),
  route("es/blog/:slug", "./routes/blog-post.tsx", { id: "post-es" }),
  route("privacy", "./routes/legal.tsx", { id: "privacy-en" }),
  route("terms", "./routes/legal.tsx", { id: "terms-en" }),
  route("es/privacidad", "./routes/legal.tsx", { id: "privacy-es" }),
  route("es/terminos", "./routes/legal.tsx", { id: "terms-es" }),
  route("en", "./routes/legacy-redirect.ts", { id: "legacy-en-root" }),
  route("en/*", "./routes/legacy-redirect.ts", { id: "legacy-en-wildcard" }),
  route("sitemap.xml", "./routes/sitemap.ts"),
  route("llms.txt", "./routes/llms.ts"),
  route("api/lead", "./routes/api-lead.ts"),
  route("api/chat", "./routes/api-chat.ts"),
  route("ops/login", "./routes/ops-login.tsx"),
  route("ops/auth/callback", "./routes/ops-auth-callback.ts"),
  route("ops", "./routes/ops-layout.tsx", [
    index("./routes/ops-index.tsx"),
    route("content", "./routes/ops-content.tsx"),
    route("content/:translationGroupId", "./routes/ops-content-detail.tsx"),
    route("briefs", "./routes/ops-briefs.tsx"),
    route("distribution", "./routes/ops-distribution.tsx"),
    route("prospects", "./routes/ops-prospects.tsx"),
    route("prospects/:id", "./routes/ops-prospect-detail.tsx"),
    route("leads", "./routes/ops-leads.tsx"),
    route("runs", "./routes/ops-runs.tsx"),
  ]),
  route("*", "./routes/not-found.tsx"),
] satisfies RouteConfig;
